# Use a base image with Python 3.11 and CUDA 12.4
FROM nvidia/cuda:12.4.0-devel-ubuntu22.04

LABEL authors="Simon Regner"

# Set environment variables for Python and CUDA
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/root/.local/bin:$PATH"

# Install Python 3.11 and dependencies
RUN apt-get update && apt-get install -y \
    python3.11 \
    python3.11-venv \
    python3.11-dev \
    build-essential \
    && apt-get clean

# Create a symbolic link to make Python 3.11 the default
RUN ln -s /usr/bin/python3.11 /usr/bin/python3 && \
    ln -s /usr/bin/pip3 /usr/bin/pip

# Install pip and additional Python libraries
RUN python3 -m ensurepip && pip install --upgrade pip

# Install other libraries required for your code
COPY detection/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Set the working directory in the container
WORKDIR /detection

# Copy your application code
COPY detection /detection

# Specify the default command to run your application
CMD ["python3", "road_detection.py"]